import { Episode } from "@/types";

export const episodes: Episode[] = [
    {
        id: 5978087,
        name: "Greek Tragedy",
        overview:
            "When two sorority sisters are found stabbed to death, the Fugitive Task Force heads to Virginia to hunt down the suspect before more killings occur. Hana agrees to meet with Ethan after he asks her for help with his latest troubles.",
        episode_number: 13,
        air_date: "February 25, 2025",
        still_path: "/qNsz0W38Vgh6ejtJ4DEMDYwsmZc.jpg",
        vote_average: 4.5,
        runtime: 42,
    },
    {
        id: 5474914,
        name: "Aquarium Drinker",
        overview:
            "When a detective is brutally murdered, the Fugitive Task Force investigates a string of gruesome killings. Meanwhile, Remy and Abby's relationship grows stronger.",
        episode_number: 1,
        air_date: "October 15, 2024",
        still_path: "/hxiEhLdTATx117HWB1DjsIkaTZa.jpg",
        vote_average: 5,
        runtime: 43,
    },
    {
        id: 5660352,
        name: "Varsity Blues",
        overview:
            "The Fugitive Task Force is called in to hunt down a missing teen from New Jersey who has a connection to a classmate's recent suicide. Meanwhile, Cora feels Ray and his father are putting too much pressure on Caleb.",
        episode_number: 2,
        air_date: "October 22, 2024",
        still_path: "/8QHtoqCkal0W8cy7MirbfdHhAbn.jpg",
        vote_average: 5,
        runtime: 43,
    },
    {
        id: 5693586,
        name: "White Buffalo",
        overview:
            "After a simple act of defiance by a couple of young climate activists goes south, the Fugitive Task Force works to hunt them down before their plans take a devastating turn. Meanwhile, Nina and Scola face family drama when they host her father and sister after they come to town.",
        episode_number: 3,
        air_date: "October 29, 2024",
        still_path: "/xdEkUd2OL9JqM5Czew8YfGxdkel.jpg",
        vote_average: 4,
        runtime: 43,
    },
    {
        id: 6047781,
        name: "Toxic Behavior",
        overview: null,
        episode_number: 16,
        air_date: "April 1, 2025",
        still_path: null,
        vote_average: null,
        runtime: null,
    },
    {
        id: 5693587,
        name: "Pig Butchering",
        overview:
            "As Barnes adjusts to living without her children full time, she and Remy butt heads when she disregards his direct orders and investigates a scam call center from where she received a distressing call from a young girl.",
        episode_number: 4,
        air_date: "November 12, 2024",
        still_path: "/tOfJTIgF0k2FwndIeBV0CLMowBA.jpg",
        vote_average: 4.5,
        runtime: 43,
    },
    {
        id: 5693588,
        name: "Money Moves",
        overview:
            "When a privately owned security corporation warehouse is robbed, the Fugitive Task Force is called in for assistance as the sophisticated team of thieves plan their next heist. Meanwhile, Ray and Cora wrestle with Caleb’s sudden desire to spend time with his biological father.",
        episode_number: 5,
        air_date: "November 19, 2024",
        still_path: "/8UAVKcTMnwr7tIMIzhMdPdUILQW.jpg",
        vote_average: null,
        runtime: 43,
    },
    {
        id: 5743842,
        name: "Pageantry",
        overview:
            "When an international beauty queen is killed on live television, the Fugitive Task Force heads to Philadelphia to hunt down the killer. Meanwhile, Hana senses that Ethan is hiding something.",
        episode_number: 6,
        air_date: "December 3, 2024",
        still_path: "/6Lh7ITOjmiUyMnXhDQTbr2xR2LN.jpg",
        vote_average: 1,
        runtime: 41,
    },
    {
        id: 5760755,
        name: "Highway to Hell",
        overview:
            "After a Queens district attorney and her husband are executed, the Fugitive Task Force uncovers a money laundering scheme connecting a violent biker gang to Wall Street. Meanwhile, Remy decides to take his relationship with Abby to a new level after he reconnects with an old friend.",
        episode_number: 7,
        air_date: "December 10, 2024",
        still_path: "/jvstQf1WnCIyhXaA3DEQ5Bx6g8m.jpg",
        vote_average: 7,
        runtime: 43,
    },
    {
        id: 5811048,
        name: "The Electric Company",
        overview:
            "The Fugitive Task Force clashes with local law enforcement in Virginia while investigating a suspected serial killer in the area. Meanwhile, Remy pushes Abby to take the next step.",
        episode_number: 8,
        air_date: "December 17, 2024",
        still_path: "/udqZOvdYhaQ248NJaet61IIRghg.jpg",
        vote_average: null,
        runtime: 43,
    },
    {
        id: 5811049,
        name: "Moving On",
        overview:
            "The Fugitive Task Force investigates a series of deadly fires involving the descendants of those who caused the infamous 1985 MOVE bombing in Philadelphia. Meanwhile, Nina's sister turns to her in a time of need.",
        episode_number: 9,
        air_date: "January 28, 2025",
        still_path: "/xsigvfHdCatSjqqhLVdRPXCgorf.jpg",
        vote_average: 7,
        runtime: 42,
    },
    {
        id: 5912485,
        name: "Ars Moriendi",
        overview:
            "After witnessing a murder in broad daylight, the Fugitive Task Force must hunt down a team of killers competing in a twisted online game. Meanwhile, Remy and Abby struggle to get on the same page.",
        episode_number: 10,
        air_date: "February 4, 2025",
        still_path: "/kr7UtJIKMUGiY4K4nAFzBHYGl5A.jpg",
        vote_average: 4.5,
        runtime: 42,
    },
    {
        id: 5912486,
        name: "Do You Realize??",
        overview:
            "The Fugitive Task Force is sent on a hunt in Philadelphia to investigate a double homicide and the abduction of a 14-year-old girl in the foster care system. Meanwhile, Ray’s father is hospitalized after an accident while helping out around the house.",
        episode_number: 11,
        air_date: "February 11, 2025",
        still_path: "/6VIDlHeGc02QKbu5QHit5zue0Sj.jpg",
        vote_average: 7,
        runtime: 44,
    },
    {
        id: 5948756,
        name: "68 Seconds",
        overview:
            "Remy calls in the Fugitive Task Force after ex-girlfriend judge April Brooks is assaulted by a serial rapist. Meanwhile, Remy decides to take the next step in his relationship with Abby after her case in New York winds down.",
        episode_number: 12,
        air_date: "February 18, 2025",
        still_path: "/wLbXGtGfUG5Kg1qOcT4EjVnRjMN.jpg",
        vote_average: 8,
        runtime: 43,
    },
    {
        id: 5978088,
        name: "100%",
        overview:
            "While helping Ethan seek treatment at a VA Hospital, Hana puts out an SOS to the Fugitive Task Force when she is among those taken hostage by an enraged veteran.",
        episode_number: 14,
        air_date: "March 11, 2025",
        still_path: "/Al8PmsmQ4LimfEYyH7GB6m0h921.jpg",
        vote_average: 4,
        runtime: 43,
    },
    {
        id: 6006874,
        name: "Four Bodies",
        overview:
            "A string of late-night murders with the same M.O. sends the Fugitive Task Force on a hunt for a serial killer with ties to a radical feminist group. Meanwhile, Nina's sister asks her for a big favor, causing a strain on Scola and Nina's relationship.",
        episode_number: 15,
        air_date: "March 18, 2025",
        still_path: "/hJb98DE2Nv8PEFSxGdVQZCBVhwY.jpg",
        vote_average: null,
        runtime: null,
    },
    {
        id: 6047782,
        name: "Gut Job",
        overview: null,
        episode_number: 17,
        air_date: "April 8, 2025",
        still_path: null,
        vote_average: null,
        runtime: null,
    },
    {
        id: 6006875,
        name: "Altered Carbon",
        overview: null,
        episode_number: 18,
        air_date: null,
        still_path: null,
        vote_average: null,
        runtime: null,
    },
];
